---
title: "Formation Git"
subtitle: "Apprendre à utiliser le gestionnaire de versions Git et la forge logicielle Gitlab en tant qu'utilisateur de R et RStudio"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation de Git pour les utilisateurs de R au MASA

slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom

toc: true
toc-title: Sommaire
toc-depth: 1
toc-float: true

# multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
---

## Avant-propos

<br>

Ce diaporama de formation a été rédigé dans le but d'être le support visuel des formations dispensées au [MASA](https://agreste.agriculture.gouv.fr/).  

Ces formations s'adressent à des agents **qui découvrent le contrôle de version**.  
Elles sont données en présentiel sur une durée **d'une journée** à partir de juin 2024.  

::: callout-note
## Champ couvert par cette formation

**Ce support ne couvre pas tous les aspects du contrôle de version ni toutes les commandes Git.**  

De même, il est orienté pour être utile aux agents du MASA et se concentre donc sur une utilisation de R via [RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à disposition des agents sur la plateforme interne Cerise basée sur RStudio Server.  

[L'utilisation avec d'autre IDE tels que [VS Code](https://code.visualstudio.com/) ou encore [Github Desktop](https://desktop.github.com/) n'est donc incluse.]{.red}  

Enfin, en tant que forge interne du MASA, les fonctionnalités principales de [Gitlab](https://about.gitlab.com/) sont présentées dans ce support. Même si la majorité des concepts de base sont équivalents, [Github](https://github.com/) n'est pas abordé dans ce diaporama de formation.
:::

{{< include 01_pourquoigit.qmd >}}

{{< include 02_basegit.qmd >}}

{{< include 03_zonesgit.qmd >}}

{{< include 04_travaillerforge.qmd >}}

{{< include 05_branches.qmd >}}

{{< include 06_bibliographie.qmd >}}



